apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
    tag: {{ .Values.image.tag }} #latest
  namespace: {{ .Values.namespace.name }}
  name: {{ .Chart.name }} #techtrends
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
      tag: {{ .Values.image.tag }}
  template:
    metadata:
      labels:
        app: techtrends
        tag: {{ .Values.image.tag }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}: {{ .Values.image.tag }}
        name: {{ .Chart.name }} #techtrends
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        ports:
            - containerPort: {{ .Values.containerPort }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenesssProbe.path }} #/healthz
            port: {{ .Values.livenesssProbe.port }} #3111
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }} #/healthz
            port: {{ .Values.readinessProbe.port }} #3111
